ThreeAugment: false
aa: rand-m9-mstd0.5-inc1
activation_tracker: false
amp: true
ampere_sparsity: false
aot_autograd: false
apex_amp: false
attn_drop_rate: 0.0
aug_repeats: 0
aug_splits: 0
batch_size: 128
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: true
checkpoint_hist: 1
class_map: ''
clip_grad: 5.0
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: 0.875
cutmix: 1.0
cutmix_minmax: null
data_dir: /datasets/imagenet_lmdb
data_len: 1281167
dataset: ''
dataset_download: false
decay_epochs: 100
decay_milestones:
- 30
- 60
decay_rate: 0.1
dist_bn: reduce
drop_block: null
drop_connect: null
drop_path: null
drop_rate: 0.0
epoch_repeats: 0.0
epochs: 310
eval_metric: top1
experiment: ''
fuser: ''
gp: null
grad_checkpointing: false
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size:
- 3
- 224
- 224
interpolation: ''
jsd_loss: false
layer_decay: null
loadcheckpoint: ''
local_rank: 0
log_dir: ./log_dir/
log_interval: 50
log_wandb: false
lr: 0.005
lr_cycle_decay: 1.0
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_ep: false
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
mesa: 1.0
mesa_start_ratio: 0.3
min_lr: 5.0e-06
mixup: 0.8
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: faster_vit_3_224
model_ema: true
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
no_saver: false
num_classes: null
opt: adamw
opt_betas:
- 0.9
- 0.999
opt_eps: 1.0e-08
output: ''
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.25
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 31
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
tag: faster_vit_3_224
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validate_only: false
validation_batch_size: null
vflip: 0.0
warmup_epochs: 35
warmup_lr: 1.0e-06
weight_decay: 0.075
worker_seeding: all
workers: 8
